version: '2'
services:
  db: 
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "63946:3306" 
    volumes:
      - db-volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app: 
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - ".:/app"
    ports: 
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
volumes:
  db-volume:
