version: '2'
services:
  db: 
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database_name
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "63946:3306" 
    volumes:
      - db-volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app: 
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - ".:/app"
    ports: 
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_NAME: database_name
      DB_PASSWORD: rootpassword
      DB_HOST: db:3306
volumes:
  db-volume:
