default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: rootpassword
  database: database_name
  host: db
  port: 3306

development:
  <<: *default
  database: database_name

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
  database: my_app_production
  username: my_production_username
  password: <%= ENV['MY_APP_DATABASE_PASSWORD'] %>
